In [1]:
import csv
import os
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
City_data_2013 = 'C:/Users/kouam/mini_project/Project_work/Raw_Data_City/City_data_2013.xlsx'
City_data_2014 = 'C:/Users/kouam/mini_project/Project_work/Raw_Data_City/City_data_2014.xlsx'
City_data_2015=  'C:/Users/kouam/mini_project/Project_work/Raw_Data_City/City_data_2015.xlsx'
City_data_2016 = 'C:/Users/kouam/mini_project/Project_work/Raw_Data_City/City_data_2016.xlsx'
City_data_2017 = 'C:/Users/kouam/mini_project/Project_work/Raw_Data_City/City_data_2017.xlsx'

In [3]:
City_2013_df = pd.read_excel(City_data_2013)
City_2014_df = pd.read_excel(City_data_2014)
City_2015_df = pd.read_excel(City_data_2015)
City_2016_df = pd.read_excel(City_data_2016)
City_2017_df = pd.read_excel(City_data_2017)

In [4]:
# City_2013_copy_df = City_2013_df.dropna(axis=1, how='all')
# City_2014_copy_df = City_2014_df.dropna(axis=1, how='all')
# City_2015_copy_df = City_2015_df.dropna(axis=1, how='all')
# City_2016_copy_df = City_2016_df.dropna(axis=1, how='all')
# City_2017_copy_df = City_2017_df.dropna(axis=1, how='all')

In [5]:
City_2013_copy_df = City_2013_df
City_2014_copy_df = City_2014_df
City_2015_copy_df = City_2015_df
City_2016_copy_df = City_2016_df
City_2017_copy_df = City_2017_df

In [6]:
City_2013_copy_df.fillna(0)
City_2014_copy_df.fillna(0)
City_2015_copy_df.fillna(0)
City_2016_copy_df.fillna(0)
City_2017_copy_df.fillna(0)

,PRIM_STATE,AREA,AREA_NAME,OCC_CODE,OCC_TITLE,OCC_GROUP,TOT_EMP,EMP_PRSE,JOBS_1000,LOC QUOTIENT,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
0,AK,11260,"Anchorage, AK",13-1111,Management Analysts,detailed,430,12.2,2.503,0.54,...,40.9,48.62,59.14,55700,68730,85070,101140,123010,0.0,0.0
1,AK,11260,"Anchorage, AK",13-1161,Market Research Analysts and Marketing Special...,detailed,350,17.7,2.013,0.48,...,32.45,44.68,56.07,37120,48850,67490,92940,116630,0.0,0.0
2,AK,11260,"Anchorage, AK",13-2031,Budget Analysts,detailed,140,5.2,0.803,2.1,...,36.34,44.72,49.66,56820,66540,75590,93020,103300,0.0,0.0
3,AK,11260,"Anchorage, AK",13-2051,Financial Analysts,detailed,290,12.1,1.685,0.82,...,43.12,58.57,74.95,49400,68530,89680,121830,155910,0.0,0.0
4,AK,11260,"Anchorage, AK",15-1121,Computer Systems Analysts,detailed,610,13.4,3.501,0.86,...,38.71,47.1,56.29,44320,60750,80520,97970,117080,0.0,0.0
5,AK,11260,"Anchorage, AK",15-1122,Information Security Analysts,detailed,60,42.4,0.355,0.48,...,45.52,51.46,70.42,48500,80360,94680,107040,146470,0.0,0.0
6,AK,11260,"Anchorage, AK",15-2031,Operations Research Analysts,detailed,70,22.5,0.403,0.54,...,35.8,46.17,80.32,41970,55800,74460,96030,167060,0.0,0.0
7,AK,21820,"Fairbanks, AK",13-1111,Management Analysts,detailed,70,3.4,1.973,0.43,...,35.18,41.58,50.05,54990,61210,73180,86480,104100,0.0,0.0
8,AK,21820,"Fairbanks, AK",13-1161,Market Research Analysts and Marketing Special...,detailed,40,16.4,1.184,0.28,...,28.79,46.86,57.01,35230,43250,59870,97460,118590,0.0,0.0
9,AK,21820,"Fairbanks, AK",13-2031,Budget Analysts,detailed,60,10.6,1.64,4.29,...,35.19,39.62,49.83,55120,62880,73190,82410,103650,0.0,0.0
10,AK,21820,"Fairbanks, AK",15-1121,Computer Systems Analysts,detailed,50,3.7,1.348,0.33,...,37.67,44.85,50.35,57340,66080,78360,93290,104720,0.0,0.0
11,AL,11500,"Anniston-Oxford-Jacksonville, AL",13-1111,Management Analysts,detailed,60,4.4,1.417,0.31,...,31.11,37.01,41.64,19930,48910,64710,76980,86610,0.0,0.0
12,AL,11500,"Anniston-Oxford-Jacksonville, AL",13-1161,Market Research Analysts and Marketing Special...,detailed,30,12,0.772,0.18,...,19.23,25.84,32.73,27910,33770,40000,53740,68080,0.0,0.0
13,AL,12220,"Auburn-Opelika, AL",13-1111,Management Analysts,detailed,60,7.9,1.143,0.25,...,33.42,48.12,62.11,30670,46300,69520,100080,129180,0.0,0.0
14,AL,12220,"Auburn-Opelika, AL",13-1161,Market Research Analysts and Marketing Special...,detailed,80,12.5,1.397,0.33,...,19.41,25.96,36.3,24070,32820,40360,53990,75510,0.0,0.0
15,AL,12220,"Auburn-Opelika, AL",15-1121,Computer Systems Analysts,detailed,60,31.8,1.094,0.27,...,29.75,35.29,39.81,52610,56090,61880,73400,82810,0.0,0.0
16,AL,13820,"Birmingham-Hoover, AL",13-1111,Management Analysts,detailed,1200,11.2,2.376,0.51,...,30.74,45.39,63.6,33190,47020,63930,94410,132290,0.0,0.0
17,AL,13820,"Birmingham-Hoover, AL",13-1161,Market Research Analysts and Marketing Special...,detailed,1320,7.6,2.608,0.62,...,28.16,38.92,48.99,27360,41700,58580,80950,101890,0.0,0.0
18,AL,13820,"Birmingham-Hoover, AL",13-2031,Budget Analysts,detailed,160,11.8,0.323,0.84,...,35.55,45.43,54.63,52160,59080,73950,94490,113640,0.0,0.0
19,AL,13820,"Birmingham-Hoover, AL",13-2041,Credit Analysts,detailed,330,6.6,0.646,1.23,...,34.39,47.62,68.18,47680,56670,71540,99060,141810,0.0,0.0
20,AL,13820,"Birmingham-Hoover, AL",13-2051,Financial Analysts,detailed,690,7,1.375,0.67,...,38.21,48.39,63.38,51050,62890,79480,100660,131830,0.0,0.0
21,AL,13820,"Birmingham-Hoover, AL",15-1121,Computer Systems Analysts,detailed,1590,18.4,3.161,0.77,...,35.98,42.89,48.69,53790,62720,74840,89200,101270,0.0,0.0
22,AL,13820,"Birmingham-Hoover, AL",15-1122,Information Security Analysts,detailed,410,14.8,0.821,1.11,...,44.15,54.88,62.89,55860,67720,91830,114150,130810,0.0,0.0
23,AL,13820,"Birmingham-Hoover, AL",15-2031,Operations Research Analysts,detailed,100,4.7,0.194,0.26,...,36.17,48.4,60.1,50170,59630,75230,100660,125000,0.0,0.0
24,AL,19300,"Daphne-Fairhope-Foley, AL",13-1111,Management Analysts,detailed,90,25.5,1.309,0.28,...,38.53,45.23,48.8,43980,59440,80150,94070,101510,0.0,0.0
25,AL,19300,"Daphne-Fairhope-Foley, AL",13-1161,Market Research Analysts and Marketing Special...,detailed,130,19.1,1.858,0.44,...,20.37,30.05,36.55,23650,32380,42370,62500,76020,0.0,0.0
26,AL,19460,"Decatur, AL",13-1111,Management Analysts,detailed,90,21,1.659,0.36,...,21.21,30.09,46.73,28590,34210,44120,62590,97190,0.0,0.0
27,AL,19460,"Decatur, AL",13-1161,Market Research Analysts and Marketing Special...,detailed,40,27.7,0.782,0.19,...,32.71,38.18,48.07,32800,45760,68040,79420,99980,0.0,0.0
28,AL,19460,"Decatur, AL",15-1121,Computer Systems Analysts,detailed,40,9.4,0.675,0.17,...,42.44,51.93,60.08,47250,71210,88280,108020,124970,0.0,0.0
29,AL,20020,"Dothan, AL",13-1111,Management Analysts,detailed,40,34.3,0.793,0.17,...,24.03,46.05,62.86,33860,41860,49970,95790,130750,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,IL,16580,"Champaign-Urbana, IL",15-1122,Information Security Analysts,detailed,80,37,0.768,1.04,...,43.52,54.12,63.87,56080,71080,90520,112570,132860,0.0,0.0
708,IL,16974,"Chicago-Naperville-Arlington Heights, IL Metro...",13-1111,Management Analysts,detailed,28640,5.5,7.82,1.69,...,37.67,53.07,77.72,37250,54970,78340,110380,161650,0.0,0.0
709,IL,16974,"Chicago-Naperville-Arlington Heights, IL Metro...",13-1161,Market Research Analysts and Marketing Special...,detailed,17680,4.1,4.826,1.15,...,28.17,36.71,47.4,31640,43620,58590,76350,98600,0.0,0.0
710,IL,16974,"Chicago-Naperville-Arlington Heights, IL Metro...",13-2031,Budget Analysts,detailed,970,10,0.264,0.69,...,34.97,43.67,51.76,53010,59660,72740,90830,107670,0.0,0.0
711,IL,16974,"Chicago-Naperville-Arlington Heights, IL Metro...",13-2041,Credit Analysts,detailed,2300,8.6,0.627,1.19,...,32.52,42.16,60.89,42370,53990,67640,87680,126650,0.0,0.0
712,IL,16974,"Chicago-Naperville-Arlington Heights, IL Metro...",13-2051,Financial Analysts,detailed,11130,5.6,3.038,1.47,...,37.65,47.9,63.14,50820,61010,78310,99630,131330,0.0,0.0
713,IL,16974,"Chicago-Naperville-Arlington Heights, IL Metro...",15-1121,Computer Systems Analysts,detailed,17990,9.1,4.912,1.2,...,43.08,52.94,62.79,54670,70750,89600,110110,130610,0.0,0.0
714,IL,16974,"Chicago-Naperville-Arlington Heights, IL Metro...",15-1122,Information Security Analysts,detailed,3030,11.3,0.826,1.12,...,46.22,59.14,71.86,59060,74090,96130,123020,149460,0.0,0.0
715,IL,16974,"Chicago-Naperville-Arlington Heights, IL Metro...",15-2031,Operations Research Analysts,detailed,2610,7.5,0.712,0.96,...,40.88,49.74,62.11,57800,69510,85020,103460,129180,0.0,0.0
716,IL,19180,"Danville, IL",13-1111,Management Analysts,detailed,**,**,**,**,...,35.85,42.79,55.23,42610,49760,74580,89010,114880,0.0,0.0
717,IL,19500,"Decatur, IL",13-1161,Market Research Analysts and Marketing Special...,detailed,**,**,**,**,...,22.66,29.99,51.11,33710,38680,47140,62380,106300,0.0,0.0
718,IL,19500,"Decatur, IL",15-1121,Computer Systems Analysts,detailed,40,3.4,0.876,0.21,...,36.09,44.88,51.95,52040,59680,75070,93360,108050,0.0,0.0
719,IL,20994,"Elgin, IL Metropolitan Division",13-1111,Management Analysts,detailed,560,12.5,2.23,0.48,...,29.23,38.21,55.58,19090,42230,60790,79480,115610,0.0,0.0
720,IL,20994,"Elgin, IL Metropolitan Division",13-1161,Market Research Analysts and Marketing Special...,detailed,730,12.6,2.884,0.69,...,26.08,33.26,40.37,31780,40840,54240,69190,83960,0.0,0.0
721,IL,20994,"Elgin, IL Metropolitan Division",13-2041,Credit Analysts,detailed,170,34.9,0.681,1.3,...,24.7,31.4,43.47,22330,25010,51370,65320,90420,0.0,0.0
722,IL,20994,"Elgin, IL Metropolitan Division",13-2051,Financial Analysts,detailed,260,23.4,1.048,0.51,...,34.42,39.18,45.63,44190,58310,71590,81490,94920,0.0,0.0
723,IL,20994,"Elgin, IL Metropolitan Division",15-1121,Computer Systems Analysts,detailed,530,19.4,2.107,0.52,...,37.52,47.59,57.97,50430,64590,78030,98990,120570,0.0,0.0
724,IL,20994,"Elgin, IL Metropolitan Division",15-1122,Information Security Analysts,detailed,30,19,0.12,0.16,...,40.42,53.28,59.5,62640,70720,84080,110830,123760,0.0,0.0
725,IL,20994,"Elgin, IL Metropolitan Division",15-2031,Operations Research Analysts,detailed,100,31.9,0.415,0.56,...,40.07,49.38,66.83,49540,65180,83340,102710,139000,0.0,0.0
726,IL,28100,"Kankakee, IL",13-1111,Management Analysts,detailed,150,27.6,3.479,0.75,...,32.89,45.03,63.39,22230,42260,68410,93660,131850,0.0,0.0
727,IL,28100,"Kankakee, IL",13-1161,Market Research Analysts and Marketing Special...,detailed,60,28,1.373,0.33,...,19.26,26.29,33.97,23830,30550,40050,54670,70650,0.0,0.0
728,IL,28100,"Kankakee, IL",15-1121,Computer Systems Analysts,detailed,40,12,0.834,0.2,...,41.78,46.92,50.21,62070,72790,86910,97600,104430,0.0,0.0
729,IL,29404,"Lake County-Kenosha County, IL-WI Metropolitan...",13-1111,Management Analysts,detailed,3230,10.1,7.938,1.72,...,44.96,60,96.06,48100,67140,93510,124800,199810,0.0,0.0
730,IL,29404,"Lake County-Kenosha County, IL-WI Metropolitan...",13-1161,Market Research Analysts and Marketing Special...,detailed,2150,12.8,5.279,1.26,...,33.08,43.83,58.73,35930,50320,68800,91170,122150,0.0,0.0
731,IL,29404,"Lake County-Kenosha County, IL-WI Metropolitan...",13-2031,Budget Analysts,detailed,100,22.6,0.238,0.62,...,34.29,39.76,48.18,54850,60360,71330,82700,100220,0.0,0.0
732,IL,29404,"Lake County-Kenosha County, IL-WI Metropolitan...",13-2041,Credit Analysts,detailed,180,21,0.435,0.83,...,28.93,39.12,61.13,43200,48400,60170,81370,127160,0.0,0.0
733,IL,29404,"Lake County-Kenosha County, IL-WI Metropolitan...",13-2051,Financial Analysts,detailed,970,20.2,2.383,1.16,...,47.42,#,#,59670,75480,98630,#,#,0.0,0.0
734,IL,29404,"Lake County-Kenosha County, IL-WI Metropolitan...",15-1121,Computer Systems Analysts,detailed,1960,19.3,4.821,1.18,...,42.76,54.12,63.09,56630,67250,88940,112560,131220,0.0,0.0
735,IL,29404,"Lake County-Kenosha County, IL-WI Metropolitan...",15-1122,Information Security Analysts,detailed,290,36.1,0.711,0.96,...,48.18,60.46,72.48,66500,79930,100220,125760,150760,0.0,0.0
736,IL,29404,"Lake County-Kenosha County, IL-WI Metropolitan...",15-2031,Operations Research Analysts,detailed,**,**,**,**,...,37.71,50.23,60.46,36240,55580,78430,104470,125760,0.0,0.0

In [7]:
City_2013_copy_df['Year'] = '2013'
City_2014_copy_df['Year'] = '2014'
City_2015_copy_df['Year'] = '2015'
City_2016_copy_df['Year'] = '2016'
City_2017_copy_df['Year'] = '2017'

In [8]:
City_2013_copy_df.fillna(0)
City_2014_copy_df.fillna(0)
City_2015_copy_df.fillna(0)
City_2015_copy_df.fillna(0)
City_2017_copy_df.fillna(0)

,PRIM_STATE,AREA,AREA_NAME,OCC_CODE,OCC_TITLE,OCC_GROUP,TOT_EMP,EMP_PRSE,JOBS_1000,LOC QUOTIENT,...,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY,Year
0,AK,11260,"Anchorage, AK",13-1111,Management Analysts,detailed,430,12.2,2.503,0.54,...,48.62,59.14,55700,68730,85070,101140,123010,0.0,0.0,2017
1,AK,11260,"Anchorage, AK",13-1161,Market Research Analysts and Marketing Special...,detailed,350,17.7,2.013,0.48,...,44.68,56.07,37120,48850,67490,92940,116630,0.0,0.0,2017
2,AK,11260,"Anchorage, AK",13-2031,Budget Analysts,detailed,140,5.2,0.803,2.1,...,44.72,49.66,56820,66540,75590,93020,103300,0.0,0.0,2017
3,AK,11260,"Anchorage, AK",13-2051,Financial Analysts,detailed,290,12.1,1.685,0.82,...,58.57,74.95,49400,68530,89680,121830,155910,0.0,0.0,2017
4,AK,11260,"Anchorage, AK",15-1121,Computer Systems Analysts,detailed,610,13.4,3.501,0.86,...,47.1,56.29,44320,60750,80520,97970,117080,0.0,0.0,2017
5,AK,11260,"Anchorage, AK",15-1122,Information Security Analysts,detailed,60,42.4,0.355,0.48,...,51.46,70.42,48500,80360,94680,107040,146470,0.0,0.0,2017
6,AK,11260,"Anchorage, AK",15-2031,Operations Research Analysts,detailed,70,22.5,0.403,0.54,...,46.17,80.32,41970,55800,74460,96030,167060,0.0,0.0,2017
7,AK,21820,"Fairbanks, AK",13-1111,Management Analysts,detailed,70,3.4,1.973,0.43,...,41.58,50.05,54990,61210,73180,86480,104100,0.0,0.0,2017
8,AK,21820,"Fairbanks, AK",13-1161,Market Research Analysts and Marketing Special...,detailed,40,16.4,1.184,0.28,...,46.86,57.01,35230,43250,59870,97460,118590,0.0,0.0,2017
9,AK,21820,"Fairbanks, AK",13-2031,Budget Analysts,detailed,60,10.6,1.64,4.29,...,39.62,49.83,55120,62880,73190,82410,103650,0.0,0.0,2017
10,AK,21820,"Fairbanks, AK",15-1121,Computer Systems Analysts,detailed,50,3.7,1.348,0.33,...,44.85,50.35,57340,66080,78360,93290,104720,0.0,0.0,2017
11,AL,11500,"Anniston-Oxford-Jacksonville, AL",13-1111,Management Analysts,detailed,60,4.4,1.417,0.31,...,37.01,41.64,19930,48910,64710,76980,86610,0.0,0.0,2017
12,AL,11500,"Anniston-Oxford-Jacksonville, AL",13-1161,Market Research Analysts and Marketing Special...,detailed,30,12,0.772,0.18,...,25.84,32.73,27910,33770,40000,53740,68080,0.0,0.0,2017
13,AL,12220,"Auburn-Opelika, AL",13-1111,Management Analysts,detailed,60,7.9,1.143,0.25,...,48.12,62.11,30670,46300,69520,100080,129180,0.0,0.0,2017
14,AL,12220,"Auburn-Opelika, AL",13-1161,Market Research Analysts and Marketing Special...,detailed,80,12.5,1.397,0.33,...,25.96,36.3,24070,32820,40360,53990,75510,0.0,0.0,2017
15,AL,12220,"Auburn-Opelika, AL",15-1121,Computer Systems Analysts,detailed,60,31.8,1.094,0.27,...,35.29,39.81,52610,56090,61880,73400,82810,0.0,0.0,2017
16,AL,13820,"Birmingham-Hoover, AL",13-1111,Management Analysts,detailed,1200,11.2,2.376,0.51,...,45.39,63.6,33190,47020,63930,94410,132290,0.0,0.0,2017
17,AL,13820,"Birmingham-Hoover, AL",13-1161,Market Research Analysts and Marketing Special...,detailed,1320,7.6,2.608,0.62,...,38.92,48.99,27360,41700,58580,80950,101890,0.0,0.0,2017
18,AL,13820,"Birmingham-Hoover, AL",13-2031,Budget Analysts,detailed,160,11.8,0.323,0.84,...,45.43,54.63,52160,59080,73950,94490,113640,0.0,0.0,2017
19,AL,13820,"Birmingham-Hoover, AL",13-2041,Credit Analysts,detailed,330,6.6,0.646,1.23,...,47.62,68.18,47680,56670,71540,99060,141810,0.0,0.0,2017
20,AL,13820,"Birmingham-Hoover, AL",13-2051,Financial Analysts,detailed,690,7,1.375,0.67,...,48.39,63.38,51050,62890,79480,100660,131830,0.0,0.0,2017
21,AL,13820,"Birmingham-Hoover, AL",15-1121,Computer Systems Analysts,detailed,1590,18.4,3.161,0.77,...,42.89,48.69,53790,62720,74840,89200,101270,0.0,0.0,2017
22,AL,13820,"Birmingham-Hoover, AL",15-1122,Information Security Analysts,detailed,410,14.8,0.821,1.11,...,54.88,62.89,55860,67720,91830,114150,130810,0.0,0.0,2017
23,AL,13820,"Birmingham-Hoover, AL",15-2031,Operations Research Analysts,detailed,100,4.7,0.194,0.26,...,48.4,60.1,50170,59630,75230,100660,125000,0.0,0.0,2017
24,AL,19300,"Daphne-Fairhope-Foley, AL",13-1111,Management Analysts,detailed,90,25.5,1.309,0.28,...,45.23,48.8,43980,59440,80150,94070,101510,0.0,0.0,2017
25,AL,19300,"Daphne-Fairhope-Foley, AL",13-1161,Market Research Analysts and Marketing Special...,detailed,130,19.1,1.858,0.44,...,30.05,36.55,23650,32380,42370,62500,76020,0.0,0.0,2017
26,AL,19460,"Decatur, AL",13-1111,Management Analysts,detailed,90,21,1.659,0.36,...,30.09,46.73,28590,34210,44120,62590,97190,0.0,0.0,2017
27,AL,19460,"Decatur, AL",13-1161,Market Research Analysts and Marketing Special...,detailed,40,27.7,0.782,0.19,...,38.18,48.07,32800,45760,68040,79420,99980,0.0,0.0,2017
28,AL,19460,"Decatur, AL",15-1121,Computer Systems Analysts,detailed,40,9.4,0.675,0.17,...,51.93,60.08,47250,71210,88280,108020,124970,0.0,0.0,2017
29,AL,20020,"Dothan, AL",13-1111,Management Analysts,detailed,40,34.3,0.793,0.17,...,46.05,62.86,33860,41860,49970,95790,130750,0.0,0.0,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,IL,16580,"Champaign-Urbana, IL",15-1122,Information Security Analysts,detailed,80,37,0.768,1.04,...,54.12,63.87,56080,71080,90520,112570,132860,0.0,0.0,2017
708,IL,16974,"Chicago-Naperville-Arlington Heights, IL Metro...",13-1111,Management Analysts,detailed,28640,5.5,7.82,1.69,...,53.07,77.72,37250,54970,78340,110380,161650,0.0,0.0,2017
709,IL,16974,"Chicago-Naperville-Arlington Heights, IL Metro...",13-1161,Market Research Analysts and Marketing Special...,detailed,17680,4.1,4.826,1.15,...,36.71,47.4,31640,43620,58590,76350,98600,0.0,0.0,2017
710,IL,16974,"Chicago-Naperville-Arlington Heights, IL Metro...",13-2031,Budget Analysts,detailed,970,10,0.264,0.69,...,43.67,51.76,53010,59660,72740,90830,107670,0.0,0.0,2017
711,IL,16974,"Chicago-Naperville-Arlington Heights, IL Metro...",13-2041,Credit Analysts,detailed,2300,8.6,0.627,1.19,...,42.16,60.89,42370,53990,67640,87680,126650,0.0,0.0,2017
712,IL,16974,"Chicago-Naperville-Arlington Heights, IL Metro...",13-2051,Financial Analysts,detailed,11130,5.6,3.038,1.47,...,47.9,63.14,50820,61010,78310,99630,131330,0.0,0.0,2017
713,IL,16974,"Chicago-Naperville-Arlington Heights, IL Metro...",15-1121,Computer Systems Analysts,detailed,17990,9.1,4.912,1.2,...,52.94,62.79,54670,70750,89600,110110,130610,0.0,0.0,2017
714,IL,16974,"Chicago-Naperville-Arlington Heights, IL Metro...",15-1122,Information Security Analysts,detailed,3030,11.3,0.826,1.12,...,59.14,71.86,59060,74090,96130,123020,149460,0.0,0.0,2017
715,IL,16974,"Chicago-Naperville-Arlington Heights, IL Metro...",15-2031,Operations Research Analysts,detailed,2610,7.5,0.712,0.96,...,49.74,62.11,57800,69510,85020,103460,129180,0.0,0.0,2017
716,IL,19180,"Danville, IL",13-1111,Management Analysts,detailed,**,**,**,**,...,42.79,55.23,42610,49760,74580,89010,114880,0.0,0.0,2017
717,IL,19500,"Decatur, IL",13-1161,Market Research Analysts and Marketing Special...,detailed,**,**,**,**,...,29.99,51.11,33710,38680,47140,62380,106300,0.0,0.0,2017
718,IL,19500,"Decatur, IL",15-1121,Computer Systems Analysts,detailed,40,3.4,0.876,0.21,...,44.88,51.95,52040,59680,75070,93360,108050,0.0,0.0,2017
719,IL,20994,"Elgin, IL Metropolitan Division",13-1111,Management Analysts,detailed,560,12.5,2.23,0.48,...,38.21,55.58,19090,42230,60790,79480,115610,0.0,0.0,2017
720,IL,20994,"Elgin, IL Metropolitan Division",13-1161,Market Research Analysts and Marketing Special...,detailed,730,12.6,2.884,0.69,...,33.26,40.37,31780,40840,54240,69190,83960,0.0,0.0,2017
721,IL,20994,"Elgin, IL Metropolitan Division",13-2041,Credit Analysts,detailed,170,34.9,0.681,1.3,...,31.4,43.47,22330,25010,51370,65320,90420,0.0,0.0,2017
722,IL,20994,"Elgin, IL Metropolitan Division",13-2051,Financial Analysts,detailed,260,23.4,1.048,0.51,...,39.18,45.63,44190,58310,71590,81490,94920,0.0,0.0,2017
723,IL,20994,"Elgin, IL Metropolitan Division",15-1121,Computer Systems Analysts,detailed,530,19.4,2.107,0.52,...,47.59,57.97,50430,64590,78030,98990,120570,0.0,0.0,2017
724,IL,20994,"Elgin, IL Metropolitan Division",15-1122,Information Security Analysts,detailed,30,19,0.12,0.16,...,53.28,59.5,62640,70720,84080,110830,123760,0.0,0.0,2017
725,IL,20994,"Elgin, IL Metropolitan Division",15-2031,Operations Research Analysts,detailed,100,31.9,0.415,0.56,...,49.38,66.83,49540,65180,83340,102710,139000,0.0,0.0,2017
726,IL,28100,"Kankakee, IL",13-1111,Management Analysts,detailed,150,27.6,3.479,0.75,...,45.03,63.39,22230,42260,68410,93660,131850,0.0,0.0,2017
727,IL,28100,"Kankakee, IL",13-1161,Market Research Analysts and Marketing Special...,detailed,60,28,1.373,0.33,...,26.29,33.97,23830,30550,40050,54670,70650,0.0,0.0,2017
728,IL,28100,"Kankakee, IL",15-1121,Computer Systems Analysts,detailed,40,12,0.834,0.2,...,46.92,50.21,62070,72790,86910,97600,104430,0.0,0.0,2017
729,IL,29404,"Lake County-Kenosha County, IL-WI Metropolitan...",13-1111,Management Analysts,detailed,3230,10.1,7.938,1.72,...,60,96.06,48100,67140,93510,124800,199810,0.0,0.0,2017
730,IL,29404,"Lake County-Kenosha County, IL-WI Metropolitan...",13-1161,Market Research Analysts and Marketing Special...,detailed,2150,12.8,5.279,1.26,...,43.83,58.73,35930,50320,68800,91170,122150,0.0,0.0,2017
731,IL,29404,"Lake County-Kenosha County, IL-WI Metropolitan...",13-2031,Budget Analysts,detailed,100,22.6,0.238,0.62,...,39.76,48.18,54850,60360,71330,82700,100220,0.0,0.0,2017
732,IL,29404,"Lake County-Kenosha County, IL-WI Metropolitan...",13-2041,Credit Analysts,detailed,180,21,0.435,0.83,...,39.12,61.13,43200,48400,60170,81370,127160,0.0,0.0,2017
733,IL,29404,"Lake County-Kenosha County, IL-WI Metropolitan...",13-2051,Financial Analysts,detailed,970,20.2,2.383,1.16,...,#,#,59670,75480,98630,#,#,0.0,0.0,2017
734,IL,29404,"Lake County-Kenosha County, IL-WI Metropolitan...",15-1121,Computer Systems Analysts,detailed,1960,19.3,4.821,1.18,...,54.12,63.09,56630,67250,88940,112560,131220,0.0,0.0,2017
735,IL,29404,"Lake County-Kenosha County, IL-WI Metropolitan...",15-1122,Information Security Analysts,detailed,290,36.1,0.711,0.96,...,60.46,72.48,66500,79930,100220,125760,150760,0.0,0.0,2017
736,IL,29404,"Lake County-Kenosha County, IL-WI Metropolitan...",15-2031,Operations Research Analysts,detailed,**,**,**,**,...,50.23,60.46,36240,55580,78430,104470,125760,0.0,0.0,2017

In [9]:
City_2013 = City_2013_copy_df.replace(['#', '*','**'],[0.0, 0.0,0.0]) 
City_2014 = City_2014_copy_df.replace(['#', '*','**'],[0.0, 0.0,0.0])
City_2015 = City_2015_copy_df.replace(['#', '*','**'],[0.0, 0.0,0.0]) 
City_2016 = City_2016_copy_df.replace(['#', '*','**'],[0.0, 0.0,0.0]) 
City_2017 = City_2017_copy_df.replace(['#', '*','**'],[0.0, 0.0,0.0])

In [10]:
columns = ['ANNUAL', 'HOURLY']
City_2013.drop(columns, inplace=True, axis=1)
City_2014.drop(columns, inplace=True, axis=1)
City_2015.drop(columns, inplace=True, axis=1)
City_2016.drop(columns, inplace=True, axis=1)
City_2017.drop(columns, inplace=True, axis=1)
City_2013

,PRIM_STATE,AREA,AREA_NAME,OCC_CODE,OCC_TITLE,OCC_GROUP,TOT_EMP,EMP_PRSE,JOBS_1000,LOC QUOTIENT,...,H_PCT25,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,Year
0,AK,11260,"Anchorage, AK",13-1111,Management Analysts,detailed,460.0,10.2,2.630,0.61,...,31.16,39.41,55.06,0.00,53140.0,64810.0,81970.0,114520.0,0.0,2013
1,AK,11260,"Anchorage, AK",13-1161,Market Research Analysts and Marketing Special...,detailed,280.0,10.1,1.587,0.49,...,20.44,27.97,36.76,50.48,33740.0,42510.0,58180.0,76460.0,104990.0,2013
2,AK,11260,"Anchorage, AK",13-2031,Budget Analysts,detailed,140.0,3.0,0.814,1.84,...,30.72,36.14,44.39,58.19,55280.0,63900.0,75160.0,92330.0,121020.0,2013
3,AK,11260,"Anchorage, AK",13-2051,Financial Analysts,detailed,190.0,5.3,1.082,0.57,...,37.20,44.37,56.56,67.21,63360.0,77380.0,92280.0,117640.0,139800.0,2013
4,AK,11260,"Anchorage, AK",15-1121,Computer Systems Analysts,detailed,350.0,23.1,2.010,0.53,...,28.49,35.63,43.85,53.85,49770.0,59260.0,74100.0,91210.0,112000.0,2013
5,AK,11260,"Anchorage, AK",15-2031,Operations Research Analysts,detailed,70.0,21.5,0.384,0.70,...,29.13,34.95,45.40,77.85,43830.0,60600.0,72690.0,94430.0,161930.0,2013
6,AK,21820,"Fairbanks, AK",13-1111,Management Analysts,detailed,70.0,2.3,1.896,0.44,...,27.76,33.16,39.74,48.69,53550.0,57740.0,68970.0,82670.0,101280.0,2013
7,AK,21820,"Fairbanks, AK",13-1161,Market Research Analysts and Marketing Special...,detailed,60.0,12.5,1.658,0.51,...,19.34,26.91,31.78,35.76,28400.0,40220.0,55970.0,66090.0,74370.0,2013
8,AK,21820,"Fairbanks, AK",13-2031,Budget Analysts,detailed,40.0,0.0,1.232,2.78,...,28.31,32.81,36.29,42.15,51260.0,58880.0,68250.0,75490.0,87670.0,2013
9,AK,21820,"Fairbanks, AK",15-2031,Operations Research Analysts,detailed,60.0,15.8,1.722,3.14,...,18.56,24.31,31.90,36.57,32550.0,38610.0,50550.0,66360.0,76060.0,2013
10,AL,11500,"Anniston-Oxford, AL",13-1111,Management Analysts,detailed,60.0,14.9,1.448,0.34,...,25.91,30.35,35.08,40.79,41480.0,53890.0,63130.0,72980.0,84850.0,2013
11,AL,12220,"Auburn-Opelika, AL",13-1161,Market Research Analysts and Marketing Special...,detailed,30.0,18.0,0.649,0.20,...,21.16,33.97,45.34,53.31,37230.0,44000.0,70670.0,94300.0,110880.0,2013
12,AL,13820,"Birmingham-Hoover, AL",13-1111,Management Analysts,detailed,1110.0,11.5,2.260,0.53,...,29.43,39.33,53.11,74.58,42700.0,61220.0,81810.0,110470.0,155120.0,2013
13,AL,13820,"Birmingham-Hoover, AL",13-1161,Market Research Analysts and Marketing Special...,detailed,890.0,9.4,1.809,0.56,...,20.85,28.05,35.91,48.70,35440.0,43380.0,58340.0,74700.0,101290.0,2013
14,AL,13820,"Birmingham-Hoover, AL",13-2031,Budget Analysts,detailed,120.0,9.6,0.248,0.56,...,25.17,30.09,38.39,43.98,45520.0,52360.0,62580.0,79860.0,91480.0,2013
15,AL,13820,"Birmingham-Hoover, AL",13-2041,Credit Analysts,detailed,180.0,22.0,0.374,0.75,...,19.71,27.52,35.46,47.37,33420.0,40990.0,57250.0,73750.0,98520.0,2013
16,AL,13820,"Birmingham-Hoover, AL",13-2051,Financial Analysts,detailed,580.0,17.4,1.172,0.62,...,28.40,37.11,53.84,0.00,50210.0,59070.0,77200.0,111990.0,0.0,2013
17,AL,13820,"Birmingham-Hoover, AL",15-1121,Computer Systems Analysts,detailed,2280.0,9.6,4.638,1.21,...,29.05,34.87,41.69,46.99,49260.0,60430.0,72530.0,86710.0,97740.0,2013
18,AL,13820,"Birmingham-Hoover, AL",15-1122,Information Security Analysts,detailed,1430.0,36.9,2.915,4.95,...,31.18,39.12,45.25,52.37,50610.0,64860.0,81370.0,94120.0,108920.0,2013
19,AL,13820,"Birmingham-Hoover, AL",15-2031,Operations Research Analysts,detailed,190.0,21.2,0.391,0.71,...,25.90,35.05,47.35,54.31,44450.0,53880.0,72910.0,98490.0,112960.0,2013
20,AL,13820,"Birmingham-Hoover, AL",27-3021,Broadcast News Analysts,detailed,50.0,15.5,0.109,2.99,...,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,2013
21,AL,19460,"Decatur, AL",13-1161,Market Research Analysts and Marketing Special...,detailed,30.0,17.6,0.596,0.18,...,19.07,24.28,41.08,54.70,18320.0,39670.0,50490.0,85440.0,113780.0,2013
22,AL,19460,"Decatur, AL",15-1121,Computer Systems Analysts,detailed,30.0,26.6,0.613,0.16,...,31.24,35.59,49.08,55.66,49370.0,64970.0,74020.0,102090.0,115770.0,2013
23,AL,20020,"Dothan, AL",13-1111,Management Analysts,detailed,0.0,0.0,0.000,0.00,...,23.85,46.85,58.66,79.87,40130.0,49620.0,97450.0,122010.0,166130.0,2013
24,AL,20020,"Dothan, AL",13-1161,Market Research Analysts and Marketing Special...,detailed,60.0,20.2,1.068,0.33,...,17.08,22.40,30.87,36.27,27860.0,35520.0,46580.0,64210.0,75440.0,2013
25,AL,22520,"Florence-Muscle Shoals, AL",13-1161,Market Research Analysts and Marketing Special...,detailed,50.0,22.1,0.960,0.30,...,15.17,18.93,28.03,34.52,27730.0,31560.0,39370.0,58290.0,71790.0,2013
26,AL,22520,"Florence-Muscle Shoals, AL",15-1121,Computer Systems Analysts,detailed,30.0,11.8,0.602,0.16,...,26.06,33.92,42.67,45.62,44910.0,54200.0,70560.0,88750.0,94890.0,2013
27,AL,26620,"Huntsville, AL",13-1111,Management Analysts,detailed,2000.0,5.4,9.534,2.23,...,33.71,42.88,51.98,66.74,56780.0,70120.0,89190.0,108120.0,138820.0,2013
28,AL,26620,"Huntsville, AL",13-1161,Market Research Analysts and Marketing Special...,detailed,400.0,8.8,1.922,0.59,...,18.60,24.83,36.19,47.00,32900.0,38690.0,51650.0,75280.0,97770.0,2013
29,AL,26620,"Huntsville, AL",13-2031,Budget Analysts,detailed,590.0,7.2,2.824,6.37,...,30.14,37.96,44.71,51.98,50020.0,62690.0,78950.0,92990.0,108110.0,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1990,WV,16620,"Charleston, WV",13-2031,Budget Analysts,detailed,50.0,17.3,0.342,0.77,...,19.57,22.21,27.57,40.48,32190.0,40710.0,46200.0,57350.0,84200.0,2013
1991,WV,16620,"Charleston, WV",13-2041,Credit Analysts,detailed,30.0,30.7,0.232,0.46,...,16.45,19.46,23.80,37.75,30660.0,34220.0,40490.0,49500.0,78510.0,2013
1992,WV,16620,"Charleston, WV",13-2051,Financial Analysts,detailed,120.0,15.6,0.836,0.44,...,16.51,21.84,28.62,37.09,26190.0,34340.0,45420.0,59520.0,77160.0,2013
1993,WV,16620,"Charleston, WV",15-1121,Computer Systems Analysts,detailed,80.0,12.0,0.576,0.15,...,23.94,29.31,35.19,42.28,42060.0,49790.0,60960.0,73180.0,87950.0,2013
1994,WV,16620,"Charleston, WV",15-1122,Information Security Analysts,detailed,40.0,35.2,0.265,0.45,...,23.37,37.19,49.53,54.92,38730.0,48610.0,77360.0,103020.0,114230.0,2013
1995,WV,16620,"Charleston, WV",15-2031,Operations Research Analysts,detailed,30.0,27.9,0.216,0.39,...,20.29,22.92,31.55,40.81,38940.0,42210.0,47680.0,65620.0,84880.0,2013
1996,WV,26580,"Huntington-Ashland, WV-KY-OH",13-1111,Management Analysts,detailed,100.0,11.2,0.934,0.22,...,25.85,30.59,36.25,44.59,41400.0,53770.0,63630.0,75410.0,92740.0,2013
1997,WV,26580,"Huntington-Ashland, WV-KY-OH",13-1161,Market Research Analysts and Marketing Special...,detailed,110.0,25.2,0.999,0.31,...,15.67,21.18,27.38,35.84,25840.0,32600.0,44060.0,56950.0,74540.0,2013
1998,WV,26580,"Huntington-Ashland, WV-KY-OH",13-2031,Budget Analysts,detailed,30.0,23.8,0.301,0.68,...,27.89,30.47,34.18,36.65,48980.0,58010.0,63370.0,71100.0,76230.0,2013
1999,WV,26580,"Huntington-Ashland, WV-KY-OH",13-2051,Financial Analysts,detailed,30.0,26.3,0.311,0.16,...,18.59,22.84,31.84,36.25,33360.0,38670.0,47500.0,66230.0,75410.0,2013
2000,WV,26580,"Huntington-Ashland, WV-KY-OH",15-1121,Computer Systems Analysts,detailed,70.0,33.1,0.605,0.16,...,21.76,27.22,33.72,40.09,39290.0,45250.0,56610.0,70140.0,83390.0,2013
2001,WV,34060,"Morgantown, WV",13-1111,Management Analysts,detailed,150.0,24.1,2.355,0.55,...,22.83,32.00,40.77,51.13,29210.0,47490.0,66560.0,84800.0,106350.0,2013
2002,WV,34060,"Morgantown, WV",13-1161,Market Research Analysts and Marketing Special...,detailed,80.0,14.2,1.327,0.41,...,17.37,21.48,27.51,33.04,32060.0,36120.0,44680.0,57220.0,68720.0,2013
2003,WV,34060,"Morgantown, WV",13-2051,Financial Analysts,detailed,60.0,17.3,0.906,0.48,...,20.83,24.93,32.63,44.34,39180.0,43320.0,51850.0,67870.0,92230.0,2013
2004,WV,34060,"Morgantown, WV",15-1121,Computer Systems Analysts,detailed,120.0,23.1,1.884,0.49,...,23.92,28.45,34.10,41.96,40300.0,49750.0,59180.0,70930.0,87270.0,2013
2005,WV,37620,"Parkersburg-Marietta-Vienna, WV-OH",13-1111,Management Analysts,detailed,200.0,4.4,3.023,0.71,...,36.38,40.64,44.73,52.01,65960.0,75680.0,84540.0,93040.0,108180.0,2013
2006,WV,37620,"Parkersburg-Marietta-Vienna, WV-OH",13-1161,Market Research Analysts and Marketing Special...,detailed,90.0,20.8,1.333,0.41,...,16.08,21.02,28.86,49.79,26570.0,33450.0,43730.0,60040.0,103560.0,2013
2007,WV,37620,"Parkersburg-Marietta-Vienna, WV-OH",13-2051,Financial Analysts,detailed,30.0,25.6,0.476,0.25,...,19.20,22.24,31.53,38.51,34630.0,39930.0,46250.0,65580.0,80100.0,2013
2008,WV,37620,"Parkersburg-Marietta-Vienna, WV-OH",15-1121,Computer Systems Analysts,detailed,0.0,0.0,0.000,0.00,...,27.93,32.93,36.81,50.07,41990.0,58100.0,68490.0,76560.0,104150.0,2013
2009,WV,37620,"Parkersburg-Marietta-Vienna, WV-OH",15-2031,Operations Research Analysts,detailed,90.0,4.9,1.357,2.48,...,31.53,40.93,53.84,70.13,54060.0,65570.0,85120.0,111980.0,145870.0,2013
2010,WV,48540,"Wheeling, WV-OH",13-1111,Management Analysts,detailed,0.0,0.0,0.000,0.00,...,24.62,32.88,40.75,46.76,31900.0,51220.0,68390.0,84770.0,97260.0,2013
2011,WV,48540,"Wheeling, WV-OH",13-1161,Market Research Analysts and Marketing Special...,detailed,80.0,20.3,1.208,0.37,...,14.09,20.95,26.69,29.71,22320.0,29300.0,43570.0,55520.0,61800.0,2013
2012,WV,48540,"Wheeling, WV-OH",15-1121,Computer Systems Analysts,detailed,50.0,22.9,0.737,0.19,...,20.26,23.86,31.78,44.48,30790.0,42140.0,49630.0,66110.0,92520.0,2013
2013,WY,16220,"Casper, WY",13-1111,Management Analysts,detailed,80.0,24.3,1.858,0.43,...,32.02,36.65,43.69,78.77,47180.0,66600.0,76230.0,90880.0,163840.0,2013
2014,WY,16220,"Casper, WY",13-1161,Market Research Analysts and Marketing Special...,detailed,50.0,24.9,1.138,0.35,...,17.95,21.86,27.37,33.64,28110.0,37330.0,45460.0,56940.0,69980.0,2013
2015,WY,16940,"Cheyenne, WY",13-1111,Management Analysts,detailed,80.0,9.4,1.776,0.41,...,23.58,29.44,41.97,57.26,35150.0,49040.0,61230.0,87290.0,119100.0,2013
2016,WY,16940,"Cheyenne, WY",13-1161,Market Research Analysts and Marketing Special...,detailed,70.0,11.4,1.472,0.45,...,17.29,21.34,27.73,34.62,32330.0,35960.0,44390.0,57690.0,72000.0,2013
2017,WY,16940,"Cheyenne, WY",13-2031,Budget Analysts,detailed,40.0,0.0,0.938,2.12,...,25.86,29.44,35.29,37.49,50610.0,53780.0,61230.0,73400.0,77990.0,2013
2018,WY,16940,"Cheyenne, WY",13-2051,Financial Analysts,detailed,30.0,25.0,0.728,0.39,...,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,2013
2019,WY,16940,"Cheyenne, WY",15-1121,Computer Systems Analysts,detailed,140.0,12.3,3.223,0.84,...,25.87,30.61,35.85,43.12,30640.0,53810.0,63680.0,74570.0,89680.0,2013

In [11]:
City_2013_copy_df.columns
City_2013_copy_df.set_index('AREA_NAME')
City_2013_copy_df.dtypes

PRIM_STATE       object
AREA              int64
AREA_NAME        object
OCC_CODE         object
OCC_TITLE        object
OCC_GROUP        object
TOT_EMP          object
EMP_PRSE         object
JOBS_1000        object
LOC QUOTIENT     object
H_MEAN           object
A_MEAN           object
MEAN_PRSE        object
H_PCT10          object
H_PCT25          object
H_MEDIAN         object
H_PCT75          object
H_PCT90          object
A_PCT10          object
A_PCT25          object
A_MEDIAN         object
A_PCT75          object
A_PCT90          object
ANNUAL          float64
HOURLY          float64
Year             object
dtype: object

In [12]:
#tot_city_emp_2017 = City_2017_copy_df.groupby(["AREA_NAME","Year"], as_index=False)["TOT_EMP"].sum()
#tot_city_emp_2016 = City_2016_copy_df.groupby(["AREA_NAME","Year"], as_index=False)["TOT_EMP"].sum()
#tot_city_emp_2015 = City_2015_copy_df.groupby(["AREA_NAME","Year"], as_index=False)["TOT_EMP"].sum()
#tot_city_emp_2014 = City_2014_copy_df.groupby(["AREA_NAME","Year"], as_index=False)["TOT_EMP"].sum()
#tot_city_emp_2013 = City_2013_copy_df.groupby(["AREA_NAME"], as_index=False)["TOT_EMP"].sum()

#tot_city_emp_2013 = pd.DataFrame({'Tot_Employments':City_2013_copy_df.groupby(['AREA_NAME','Year'])['TOT_EMP'].sum()}).reset_index()


#total_city_emp_year = [tot_city_emp_2013]
#total_city_emp_year = [tot_city_emp_2017,tot_city_emp_2016,tot_city_emp_2015,tot_city_emp_2014,tot_city_emp_2013]
#total_city_emp_year

In [13]:
# pd.options.display.float_format = '{:.2f}'.format
# df_2013 = pd.DataFrame(total_city_emp_year, columns = ["AREA_NAME", "TOT_EMP"])

# df_2013

In [14]:
pd.options.display.float_format = '{:.2f}'.format
City_2013_copy_df['TOT_EMP'] = pd.to_numeric(City_2013_copy_df['TOT_EMP'],errors='coerce')
City_2013_copy_df2 = pd.DataFrame(City_2013_copy_df.groupby("AREA_NAME")["TOT_EMP"].sum())
# City_2013_copy_df2.reset_index()
# City_2013_copy_df2.index

In [15]:
# City_2013_copy_df['H_MEAN'] = pd.to_numeric(City_2013_copy_df['H_MEAN'],errors='coerce')
# City_2013_copy_df3 = pd.DataFrame(City_2013_copy_df.groupby("AREA_NAME")["H_MEAN"].mean())

# City_2013_copy_df['A_MEAN'] = pd.to_numeric(City_2013_copy_df['A_MEAN'],errors='coerce')
# City_2013_copy_df4 = pd.DataFrame(City_2013_copy_df.groupby("AREA_NAME")["A_MEAN"].mean())

# City_2013_copy_df['H_PCT10'] = pd.to_numeric(City_2013_copy_df['H_PCT10'],errors='coerce')
# City_2013_copy_df5 = pd.DataFrame(City_2013_copy_df.groupby("AREA_NAME")["H_PCT10"].mean())

# City_2013_copy_df['H_PCT25'] = pd.to_numeric(City_2013_copy_df['H_PCT25'],errors='coerce')
# City_2013_copy_df6 = pd.DataFrame(City_2013_copy_df.groupby("AREA_NAME")["H_PCT25"].mean())

# City_2013_copy_df['H_PCT75'] = pd.to_numeric(City_2013_copy_df['H_PCT75'],errors='coerce')
# City_2013_copy_df7 = pd.DataFrame(City_2013_copy_df.groupby("AREA_NAME")["H_PCT75"].mean())

# City_2013_copy_df['H_PCT90'] = pd.to_numeric(City_2013_copy_df['H_PCT90'],errors='coerce')
# City_2013_copy_df8 = pd.DataFrame(City_2013_copy_df.groupby("AREA_NAME")["H_PCT90"].mean())

# City_2013_copy_df['A_PCT10'] = pd.to_numeric(City_2013_copy_df['A_PCT10'],errors='coerce')
# City_2013_copy_df9 = pd.DataFrame(City_2013_copy_df.groupby("AREA_NAME")["A_PCT10"].mean())

# City_2013_copy_df['A_PCT25'] = pd.to_numeric(City_2013_copy_df['A_PCT25'],errors='coerce')
# City_2013_copy_df10 = pd.DataFrame(City_2013_copy_df.groupby("AREA_NAME")["A_PCT25"].mean())

# City_2013_copy_df['A_PCT75'] = pd.to_numeric(City_2013_copy_df['H_PCT75'],errors='coerce')
# City_2013_copy_df11 = pd.DataFrame(City_2013_copy_df.groupby("AREA_NAME")["A_PCT75"].mean())

# City_2013_copy_df['A_PCT90'] = pd.to_numeric(City_2013_copy_df['A_PCT90'],errors='coerce')
# City_2013_copy_df12 = pd.DataFrame(City_2013_copy_df.groupby("AREA_NAME")["A_PCT90"].mean())
# # City_2013_copy_df3.reset_index()
# # City_2013_copy_df3.index

In [16]:
# Merge the two DataFrames together based on the city they share
# City_df = pd.merge(City_2013_copy_df2, City_2013_copy_df3, on='AREA_NAME')
# City_df.head()

In [17]:
# City_2013_copy_df2.merge(City_2013_copy_df3,on='AREA_NAME').merge(City_2013_copy_df4,on='AREA_NAME')

In [22]:
#master_df['tot_emp_2013'] = City_2013_copy_df['TOT_EMP'].groupby('AREA_NAME').sum()

City_2014_copy_df['TOT_EMP'] = pd.to_numeric(City_2014_copy_df['TOT_EMP'],errors='coerce')

City_2015_copy_df['TOT_EMP'] = pd.to_numeric(City_2015_copy_df['TOT_EMP'],errors='coerce')

City_2016_copy_df['TOT_EMP'] = pd.to_numeric(City_2016_copy_df['TOT_EMP'],errors='coerce')

City_2017_copy_df['TOT_EMP'] = pd.to_numeric(City_2017_copy_df['TOT_EMP'],errors='coerce')
master_df = pd.DataFrame()
master_df['Tot_Emp_2013'] = City_2013_copy_df.groupby("AREA_NAME")["TOT_EMP"].sum()
master_df['Tot_Emp_2014'] = City_2014_copy_df.groupby("AREA_NAME")["TOT_EMP"].sum()
master_df['Tot_Emp_2015'] = City_2015_copy_df.groupby("AREA_NAME")["TOT_EMP"].sum()
master_df['Tot_Emp_2016'] = City_2016_copy_df.groupby("AREA_NAME")["TOT_EMP"].sum()
master_df['Tot_Emp_2017'] = City_2017_copy_df.groupby("AREA_NAME")["TOT_EMP"].sum()
#master_df['tot_emp_2014'] = df_2014['tot_emp'].sum()
master_df.head

<bound method NDFrame.head of                                                     Tot_Emp_2013  \
AREA_NAME
Abilene, TX                                               150.00
Aguadilla-Isabela-San Sebastian, PR                       120.00
Akron, OH                                                4420.00
Albany, GA                                                370.00
Albany-Schenectady-Troy, NY                              8540.00
Albuquerque, NM                                          4090.00
Alexandria, LA                                            150.00
Allentown-Bethlehem-Easton, PA-NJ                        3690.00
Altoona, PA                                               200.00
Amarillo, TX                                              610.00
Ames, IA                                                  560.00
Anchorage, AK                                            1490.00
Anderson, IN                                              100.00
Anderson, SC                                              190.00
Ann Arbor, MI                                            2440.00
Anniston-Oxford, AL                                        60.00
Appleton, WI                                             1060.00
Asheville, NC                                            1040.00
Athens-Clarke County, GA                                  380.00
Atlanta-Sandy Springs-Marietta, GA                      58580.00
Atlantic City-Hammonton, NJ                               590.00
Auburn-Opelika, AL                                         30.00
Augusta-Richmond County, GA-SC                           1460.00
Austin-Round Rock-San Marcos, TX                        20770.00
Bakersfield-Delano, CA                                   2190.00
Baltimore-Towson, MD                                    26610.00
Bangor, ME                                                250.00
Barnstable Town, MA                                       350.00
Baton Rouge, LA                                          2220.00
Battle Creek, MI                                          180.00
...                                                          ...
Tyler, TX                                                 580.00
Valdosta, GA                                              120.00
Vallejo-Fairfield, CA                                    1280.00
Victoria, TX                                               90.00
Vineland-Millville-Bridgeton, NJ                           90.00
Virginia Beach-Norfolk-Newport News, VA-NC              12980.00
Visalia-Porterville, CA                                   420.00
Waco, TX                                                  690.00
Warner Robins, GA                                         850.00
Warren-Troy-Farmington Hills, MI Metropolitan D...      17890.00
Washington-Arlington-Alexandria, DC-VA-MD-WV Me...     126810.00
Waterbury, CT                                             300.00
Waterloo-Cedar Falls, IA                                  480.00
Wausau, WI                                                740.00
Wenatchee-East Wenatchee, WA                              160.00
West Palm Beach-Boca Raton-Boynton Beach, FL Me...       7160.00
Wheeling, WV-OH                                           130.00
Wichita Falls, TX                                          70.00
Wichita, KS                                              2490.00
Williamsport, PA                                          200.00
Wilmington, DE-MD-NJ Metropolitan Division              10250.00
Wilmington, NC                                            750.00
Winchester, VA-WV                                         330.00
Winston-Salem, NC                                        3130.00
Worcester, MA-CT                                         3140.00
Yakima, WA                                                340.00
York-Hanover, PA                                         1020.00
Youngstown-Warren-Boardman, OH-PA                        1030.00
Yuba City, CA                                             210.00
Yuma, AZ                                                  250.00

                                                    Tot_Emp_2014  \
AREA_NAME
Abilene, TX                                                  nan
Aguadilla-Isabela-San Sebastian, PR                          nan
Akron, OH                                                    nan
Albany, GA                                                360.00
Albany-Schenectady-Troy, NY                                  nan
Albuquerque, NM                                              nan
Alexandria, LA                                               nan
Allentown-Bethlehem-Easton, PA-NJ                            nan
Altoona, PA                                                  nan
Amarillo, TX                                                 nan
Ames, IA                                                  580.00
Anchorage, AK                                            1360.00
Anderson, IN                                              150.00
Anderson, SC                                                 nan
Ann Arbor, MI                                                nan
Anniston-Oxford, AL                                       110.00
Appleton, WI                                                 nan
Asheville, NC                                                nan
Athens-Clarke County, GA                                  340.00
Atlanta-Sandy Springs-Marietta, GA                      57920.00
Atlantic City-Hammonton, NJ                                  nan
Auburn-Opelika, AL                                         30.00
Augusta-Richmond County, GA-SC                           1390.00
Austin-Round Rock-San Marcos, TX                             nan
Bakersfield-Delano, CA                                   2300.00
Baltimore-Towson, MD                                         nan
Bangor, ME                                                   nan
Barnstable Town, MA                                          nan
Baton Rouge, LA                                              nan
Battle Creek, MI                                             nan
...                                                          ...
Tyler, TX                                                    nan
Valdosta, GA                                              130.00
Vallejo-Fairfield, CA                                    1270.00
Victoria, TX                                                 nan
Vineland-Millville-Bridgeton, NJ                             nan
Virginia Beach-Norfolk-Newport News, VA-NC                   nan
Visalia-Porterville, CA                                   560.00
Waco, TX                                                     nan
Warner Robins, GA                                         800.00
Warren-Troy-Farmington Hills, MI Metropolitan D...           nan
Washington-Arlington-Alexandria, DC-VA-MD-WV Me...     123330.00
Waterbury, CT                                             310.00
Waterloo-Cedar Falls, IA                                  590.00
Wausau, WI                                                   nan
Wenatchee-East Wenatchee, WA                                 nan
West Palm Beach-Boca Raton-Boynton Beach, FL Me...       7850.00
Wheeling, WV-OH                                              nan
Wichita Falls, TX                                            nan
Wichita, KS                                                  nan
Williamsport, PA                                             nan
Wilmington, DE-MD-NJ Metropolitan Division              10950.00
Wilmington, NC                                               nan
Winchester, VA-WV                                            nan
Winston-Salem, NC                                            nan
Worcester, MA-CT                                             nan
Yakima, WA                                                   nan
York-Hanover, PA                                             nan
Youngstown-Warren-Boardman, OH-PA                            nan
Yuba City, CA                                             260.00
Yuma, AZ                                                  260.00

                                                    Tot_Emp_2015  \
AREA_NAME
Abilene, TX                                                  nan
Aguadilla-Isabela-San Sebastian, PR                          nan
Akron, OH                                                    nan
Albany, GA                                                350.00
Albany-Schenectady-Troy, NY                                  nan
Albuquerque, NM                                              nan
Alexandria, LA                                               nan
Allentown-Bethlehem-Easton, PA-NJ                            nan
Altoona, PA                                                  nan
Amarillo, TX                                                 nan
Ames, IA                                                  580.00
Anchorage, AK                                            1830.00
Anderson, IN                                                 nan
Anderson, SC                                                 nan
Ann Arbor, MI                                                nan
Anniston-Oxford, AL                                          nan
Appleton, WI                                                 nan
Asheville, NC                                                nan
Athens-Clarke County, GA                                  400.00
Atlanta-Sandy Springs-Marietta, GA                           nan
Atlantic City-Hammonton, NJ                                  nan
Auburn-Opelika, AL                                         50.00
Augusta-Richmond County, GA-SC                           1530.00
Austin-Round Rock-San Marcos, TX                             nan
Bakersfield-Delano, CA                                       nan
Baltimore-Towson, MD                                         nan
Bangor, ME                                                   nan
Barnstable Town, MA                                          nan
Baton Rouge, LA                                              nan
Battle Creek, MI                                             nan
...                                                          ...
Tyler, TX                                                    nan
Valdosta, GA                                              100.00
Vallejo-Fairfield, CA                                    1380.00
Victoria, TX                                                 nan
Vineland-Millville-Bridgeton, NJ                             nan
Virginia Beach-Norfolk-Newport News, VA-NC                   nan
Visalia-Porterville, CA                                   450.00
Waco, TX                                                     nan
Warner Robins, GA                                         730.00
Warren-Troy-Farmington Hills, MI Metropolitan D...           nan
Washington-Arlington-Alexandria, DC-VA-MD-WV Me...     119190.00
Waterbury, CT                                             460.00
Waterloo-Cedar Falls, IA                                  530.00
Wausau, WI                                                   nan
Wenatchee-East Wenatchee, WA                                 nan
West Palm Beach-Boca Raton-Boynton Beach, FL Me...           nan
Wheeling, WV-OH                                              nan
Wichita Falls, TX                                            nan
Wichita, KS                                                  nan
Williamsport, PA                                             nan
Wilmington, DE-MD-NJ Metropolitan Division              12280.00
Wilmington, NC                                               nan
Winchester, VA-WV                                            nan
Winston-Salem, NC                                            nan
Worcester, MA-CT                                             nan
Yakima, WA                                                   nan
York-Hanover, PA                                             nan
Youngstown-Warren-Boardman, OH-PA                            nan
Yuba City, CA                                             350.00
Yuma, AZ                                                  130.00

                                                    Tot_Emp_2016  Tot_Emp_2017
AREA_NAME
Abilene, TX                                                  nan           nan
Aguadilla-Isabela-San Sebastian, PR                          nan           nan
Akron, OH                                                    nan           nan
Albany, GA                                                320.00        320.00
Albany-Schenectady-Troy, NY                                  nan           nan
Albuquerque, NM                                              nan           nan
Alexandria, LA                                               nan           nan
Allentown-Bethlehem-Easton, PA-NJ                            nan           nan
Altoona, PA                                                  nan           nan
Amarillo, TX                                                 nan           nan
Ames, IA                                                  600.00        550.00
Anchorage, AK                                            1840.00       1950.00
Anderson, IN                                                 nan           nan
Anderson, SC                                                 nan           nan
Ann Arbor, MI                                                nan           nan
Anniston-Oxford, AL                                          nan           nan
Appleton, WI                                                 nan           nan
Asheville, NC                                                nan           nan
Athens-Clarke County, GA                                  510.00        590.00
Atlanta-Sandy Springs-Marietta, GA                           nan           nan
Atlantic City-Hammonton, NJ                                  nan           nan
Auburn-Opelika, AL                                         70.00        200.00
Augusta-Richmond County, GA-SC                           1640.00       1890.00
Austin-Round Rock-San Marcos, TX                             nan           nan
Bakersfield-Delano, CA                                       nan           nan
Baltimore-Towson, MD                                         nan           nan
Bangor, ME                                                   nan           nan
Barnstable Town, MA                                          nan           nan
Baton Rouge, LA                                              nan           nan
Battle Creek, MI                                             nan           nan
...                                                          ...           ...
Tyler, TX                                                    nan           nan
Valdosta, GA                                              100.00        280.00
Vallejo-Fairfield, CA                                    1360.00       1430.00
Victoria, TX                                                 nan           nan
Vineland-Millville-Bridgeton, NJ                             nan           nan
Virginia Beach-Norfolk-Newport News, VA-NC                   nan           nan
Visalia-Porterville, CA                                   490.00        550.00
Waco, TX                                                     nan           nan
Warner Robins, GA                                         890.00        840.00
Warren-Troy-Farmington Hills, MI Metropolitan D...           nan           nan
Washington-Arlington-Alexandria, DC-VA-MD-WV Me...     125660.00     130530.00
Waterbury, CT                                             340.00        330.00
Waterloo-Cedar Falls, IA                                  690.00        670.00
Wausau, WI                                                   nan           nan
Wenatchee-East Wenatchee, WA                                 nan           nan
West Palm Beach-Boca Raton-Boynton Beach, FL Me...           nan           nan
Wheeling, WV-OH                                              nan           nan
Wichita Falls, TX                                            nan           nan
Wichita, KS                                                  nan           nan
Williamsport, PA                                             nan           nan
Wilmington, DE-MD-NJ Metropolitan Division              13040.00      12460.00
Wilmington, NC                                               nan           nan
Winchester, VA-WV                                            nan           nan
Winston-Salem, NC                                            nan           nan
Worcester, MA-CT                                             nan           nan
Yakima, WA                                                   nan           nan
York-Hanover, PA                                             nan           nan
Youngstown-Warren-Boardman, OH-PA                            nan           nan
Yuba City, CA                                             330.00        230.00
Yuma, AZ                                                  280.00        250.00

[381 rows x 5 columns]>

In [20]:
City_2014['A_MEDIAN'] = pd.to_numeric(City_2014['A_MEDIAN'],errors='coerce')

City_2015['A_MEDIAN'] = pd.to_numeric(City_2015['A_MEDIAN'],errors='coerce')

City_2016['A_MEDIAN'] = pd.to_numeric(City_2016['A_MEDIAN'],errors='coerce')

City_2017['A_MEDIAN'] = pd.to_numeric(City_2017['A_MEDIAN'],errors='coerce')

master_df2 = pd.DataFrame()
master_df2['Average_Sal_2013'] = City_2013.groupby("AREA_NAME")["A_MEDIAN"].mean()
master_df2['Average_Sal_2014'] = City_2014.groupby("AREA_NAME")["A_MEDIAN"].mean()
master_df2['Average_Sal_2015'] = City_2015.groupby("AREA_NAME")["A_MEDIAN"].mean()
master_df2['Average_Sal_2016'] = City_2016.groupby("AREA_NAME")["A_MEDIAN"].mean()
master_df2['Average_Sal_2017'] = City_2017.groupby("AREA_NAME")["A_MEDIAN"].mean()
#master_df['tot_emp_2014'] = df_2014['tot_emp'].sum()
master_df2.head(80)

,Average_Sal_2013,Average_Sal_2014,Average_Sal_2015,Average_Sal_2016,Average_Sal_2017
AREA_NAME,,,,,
"Abilene, TX",59210.00,nan,nan,nan,nan
"Aguadilla-Isabela-San Sebastian, PR",43010.00,nan,nan,nan,nan
"Akron, OH",66915.00,nan,nan,nan,nan
"Albany, GA",55003.33,60613.33,62416.67,61440.00,60416.67
"Albany-Schenectady-Troy, NY",70882.50,nan,nan,nan,nan
"Albuquerque, NM",70293.75,nan,nan,nan,nan
"Alexandria, LA",53340.00,nan,nan,nan,nan
"Allentown-Bethlehem-Easton, PA-NJ",69175.00,nan,nan,nan,nan
"Altoona, PA",55880.00,nan,nan,nan,nan
"Amarillo, TX",66641.67,nan,nan,nan,nan
"Ames, IA",67323.33,65943.33,67003.33,66476.67,66120.00
"Anchorage, AK",75730.00,79248.57,69204.29,79304.29,81070.00
"Anderson, IN",58600.00,69916.67,nan,nan,nan
"Anderson, SC",55950.00,nan,nan,nan,nan
"Ann Arbor, MI",72001.43,nan,nan,nan,nan
"Anniston-Oxford, AL",63130.00,60305.00,nan,nan,nan
"Appleton, WI",63648.33,nan,nan,nan,nan
"Asheville, NC",56825.71,nan,nan,nan,nan
"Athens-Clarke County, GA",54020.00,60804.00,57126.00,54928.00,53752.50
"Atlanta-Sandy Springs-Marietta, GA",71330.00,72247.50,nan,nan,nan
"Atlantic City-Hammonton, NJ",71242.00,nan,nan,nan,nan
"Auburn-Opelika, AL",70670.00,44640.00,54085.00,55010.00,57253.33
"Augusta-Richmond County, GA-SC",60472.50,68317.14,67535.71,69547.50,67682.50
"Austin-Round Rock-San Marcos, TX",77155.00,nan,nan,nan,nan
"Bakersfield-Delano, CA",83830.00,81133.75,nan,nan,nan
"Baltimore-Towson, MD",70200.00,nan,nan,nan,nan
"Bangor, ME",61333.33,nan,nan,nan,nan
"Barnstable Town, MA",81375.00,nan,nan,nan,nan
"Baton Rouge, LA",49325.71,nan,nan,nan,nan
"Battle Creek, MI",64690.00,nan,nan,nan,nan
...,...,...,...,...,...
"Brunswick, GA",61600.00,61730.00,61136.67,67076.67,70616.67
"Buffalo-Niagara Falls, NY",66990.00,nan,nan,nan,nan
"Burlington, NC",65383.33,nan,nan,nan,nan
"Burlington-South Burlington, VT",60634.29,nan,nan,nan,nan
"Camden, NJ Metropolitan Division",77302.50,nan,nan,nan,nan
"Canton-Massillon, OH",57230.00,nan,nan,nan,nan
"Cape Coral-Fort Myers, FL",69348.57,66537.50,63314.29,62184.00,62391.67
"Cape Girardeau-Jackson, MO-IL",56110.00,nan,nan,nan,nan
"Carson City, NV",57553.33,nan,nan,nan,nan
"Casper, WY",60845.00,nan,nan,nan,nan
"Cedar Rapids, IA",64571.43,66858.57,69025.00,72230.00,73244.29
"Champaign-Urbana, IL",67608.00,68688.33,69825.71,70388.33,73184.00
"Charleston, WV",52031.25,nan,nan,nan,nan
"Charleston-North Charleston-Summerville, SC",59582.86,nan,nan,nan,nan
"Charlotte-Gastonia-Rock Hill, NC-SC",66625.56,nan,nan,nan,nan
"Charlottesville, VA",74170.00,nan,nan,nan,nan
"Chattanooga, TN-GA",70430.00,nan,nan,nan,nan
"Cheyenne, WY",46106.00,nan,nan,nan,nan
"Chicago-Joliet-Naperville, IL Metropolitan Division",75450.00,77365.00,nan,nan,nan
"Chico, CA",67387.50,63396.67,59533.33,56962.00,54324.00
"Cincinnati-Middletown, OH-KY-IN",68242.50,nan,nan,nan,nan
"Clarksville, TN-KY",53665.00,nan,nan,nan,nan
"Cleveland, TN",53570.00,nan,nan,nan,nan
"Cleveland-Elyria-Mentor, OH",69270.00,nan,nan,nan,nan
"Coeur d'Alene, ID",76846.67,82523.33,58693.33,61953.33,64703.33
"College Station-Bryan, TX",63206.67,nan,nan,nan,nan
"Colorado Springs, CO",78648.75,72025.00,84195.00,85441.25,85203.75
"Columbia, MO",60777.50,nan,nan,nan,nan
"Columbia, SC",60368.75,nan,nan,nan,nan
"Columbus, GA-AL",56465.00,58994.00,59248.33,61930.00,65922.86