In [ ]:
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import csv\n",
    "import os\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "National_data_2013 = 'Project_work/Raw_Data_National/National_Data_2013.xlsx'\n",
    "National_data_2014 = 'Project_work/Raw_Data_National/National_Data_2014.xlsx'\n",
    "National_data_2015=  'Project_work/Raw_Data_National/National_Data_2015.xlsx'\n",
    "National_data_2016 = 'Project_work/Raw_Data_National/National_Data_2016.xlsx'\n",
    "National_data_2017 = 'Project_work/Raw_Data_National/National_Data_2017.xlsx'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "National_2013_df = pd.read_excel(National_data_2013)\n",
    "National_2014_df = pd.read_excel(National_data_2014)\n",
    "National_2015_df = pd.read_excel(National_data_2015)\n",
    "National_2016_df = pd.read_excel(National_data_2016)\n",
    "National_2017_df = pd.read_excel(National_data_2017)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "National_2013_copy_df = National_2013_df.dropna(axis=1, how='all')\n",
    "National_2014_copy_df = National_2014_df.dropna(axis=1, how='all')\n",
    "National_2015_copy_df = National_2015_df.dropna(axis=1, how='all')\n",
    "National_2016_copy_df = National_2016_df.dropna(axis=1, how='all')\n",
    "National_2017_copy_df = National_2017_df.dropna(axis=1, how='all')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Index(['OCC_CODE', 'OCC_TITLE', 'OCC_GROUP', 'TOT_EMP', 'EMP_PRSE', 'H_MEAN',\n",
       "       'A_MEAN', 'MEAN_PRSE', 'H_PCT10', 'H_PCT25', 'H_MEDIAN', 'H_PCT75',\n",
       "       'H_PCT90', 'A_PCT10', 'A_PCT25', 'A_MEDIAN', 'A_PCT75', 'A_PCT90'],\n",
       "      dtype='object')"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "National_2013_copy_df.columns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "tot_emp_2017 = National_2017_copy_df[\"TOT_EMP\"].sum()\n",
    "tot_emp_2016 = National_2016_copy_df[\"TOT_EMP\"].sum()\n",
    "tot_emp_2015 = National_2015_copy_df[\"TOT_EMP\"].sum()\n",
    "tot_emp_2014 = National_2014_copy_df[\"TOT_EMP\"].sum()\n",
    "tot_emp_2013 = National_2013_copy_df[\"TOT_EMP\"].sum()\n",
    "total_emp_year = [tot_emp_2017,tot_emp_2016,tot_emp_2015,tot_emp_2014,tot_emp_2013]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Total_emp_year</th>\n",
       "      <th>Year</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2478120</td>\n",
       "      <td>2017</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2385610</td>\n",
       "      <td>2016</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2262160</td>\n",
       "      <td>2015</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2144490</td>\n",
       "      <td>2014</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2036710</td>\n",
       "      <td>2013</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   Total_emp_year  Year\n",
       "0         2478120  2017\n",
       "1         2385610  2016\n",
       "2         2262160  2015\n",
       "3         2144490  2014\n",
       "4         2036710  2013"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df = pd.DataFrame({\"Total_emp_year\":total_emp_year,\"Year\":[\"2017\",\"2016\",\"2015\",\"2014\",\"2013\"]})\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}